apiVersion: v1
kind: Service
metadata:
  name: qwen3-4b
  namespace: inference
spec:
  ports:
    - name: http-qwen3-4b
      port: 80
      protocol: TCP
      targetPort: 8000
  # The label selector should match the deployment labels & it is useful for prefix caching feature
  selector:
    app: qwen3-4b
  sessionAffinity: None
  type: ClusterIP
